### ISSUE TITLE
Active floated label inputs inherit background color of container

### ISSUE THREAD

**Issue by kevinwhoffman** [WordImpress/Give#2155]
## Issue Overview
New floated label styles were introduced in Give 1.8.13 which are causing the inputs to inherit the background color of the container.

Relevant Commit: https://github.com/WordImpress/Give/commit/8926269d45b044076b4e44784a8d1f7d0a3d47a6#diff-fad886f2a982e934126ca13bc8823d06

## Expected Behavior

Form input backgrounds should not be affected by the background color of the container.

## Current Behavior

Form inputs inherit the background-color of the container if the following conditions are met:

1. Floated labels are activated.
2. The input has a value (not just a placeholder).
3. The input is not focused.

## Possible Solution
```css
// Fixes background color of floated label inputs in Give 1.8.13.
// Has no effect in Give 1.8.12.

[id*=give-form] .fl-form.fl-style-give input.fl-input, [id*=give-form] .fl-form.fl-style-give select.fl-select, [id*=give-form] .fl-form.fl-style-give textarea.fl-textarea {
    background-color: #FFFFFF;
}
```

## Screenshots

The Last Name field below meets the 3 conditions and exhibits the buggy behavior:

![image](https://user-images.githubusercontent.com/1938671/31032848-bc76c1f6-a52b-11e7-856d-38368fbd8763.png)

![image](https://user-images.githubusercontent.com/1938671/31032832-b338f366-a52b-11e7-93c1-bf01f6f34a1e.png)

## Steps to Reproduce (for bugs)
1. Install Give 1.8.13
2. Create new form with floated label inputs.
3. Ensure you are using a theme with a non-white background, or edit the page container in dev tools to make the background non-white.
3. Populate one of the inputs and then defocus it.
4. Notice that the background-color of the container is inherited for floated label inputs that 1) have a value and 2) are defocused.

## Related Issues and/or PRs

First reported: https://secure.helpscout.net/conversation/440708214/10649/?folderId=672199
First introduced: https://github.com/WordImpress/Give/commit/8926269d45b044076b4e44784a8d1f7d0a3d47a6#diff-fad886f2a982e934126ca13bc8823d06

## Todos
- [ ] Tests
- [ ] Documentation
